sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sidbhasin13/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sidbhasin13/docker-react npm run test
